#ifndef DISPLAYBLOCK_GLOBAL_H
#define DISPLAYBLOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DISPLAYBLOCK_LIBRARY)
#  define DISPLAYBLOCKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DISPLAYBLOCKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYBLOCK_GLOBAL_H
